### ISSUE TITLE
Local Files中点击Folder的文件夹，执行add to play list后无效果

### ISSUE THREAD

**Issue by JerryMissTom** [ryanhoo/StylishMusicPlayer#16]

**Comment by ryanhoo** [comment]
在 #9 发生后，去操作 Play List 确实发生了这样的事情，但是 #9 修复后，就没能复现这个 bug 了，触发它有其他的复现步骤吗？@JerryMissTom

**Comment by JerryMissTom** [comment]
修复后确实没有这个bug了。

**Comment by ryanhoo** [comment]
@JerryMissTom Thanks, you've helped me finding so many bugs. You are the best!

**Comment by JerryMissTom** [comment]
准确是我应该感谢你开源了这样一个好的项目，我从中学到了很多。虽然里面有一些bug，但是瑕不掩瑜。我fork此项目后，在工作之余花了近一周的时间来理解它，同时写了大量的注释，还专门画了它的框架图。我会继续研究它，发现bug后建立issue来反馈

**Comment by ryanhoo** [comment]
@JerryMissTom 依然非常感谢你的支持，可以看看这个 #17，加入 Gitter 或者 Slack 群组，如果有小问题的话随时问，我可以收到推送。
