### ISSUE TITLE
谢谢

### ISSUE THREAD

**Issue by wangchang163** [ryanhoo/StylishMusicPlayer#2]
在all里面，我添加到收藏的音乐出不来，一直在加载，还有默认的文件夹没有音乐，建议遍历文件夹获取音乐列表，setting里面并没有相应功能，大胸弟代码质量好高，包括封装之类的，希望博客里能对代码做一下解析，像RxJava，RxBus等

**Comment by ryanhoo** [comment]
本地文件出不来应该是 issue #3 导致的，这个项目我还没写完就跑到北京去给各路神仙拜山头了，本来没打算放出来，不知道怎么就上了 Github Trends……这两天电脑还黑屏，我下午得拿去南京东路修理，完了去杭州面基，再之后应该就可以开工了。欢迎提 bug 以及 pull request. 😘

**Comment by jp1017** [comment]
@ryanhoo 非常不错，哈哈，期待ing. :smile:

**Comment by ryanhoo** [comment]
@jp1017 thanks

**Comment by dinuscxj** [comment]
@ryanhoo 代码家在干货给你推广啦 👍

**Comment by liuzheng9110** [comment]
我是从 秋百万 微博过来的

**Comment by xiaofeiMophsic** [comment]
给顶一下 :+1: :+1:

**Comment by ryanhoo** [comment]
Thanks fellows.
