### ISSUE TITLE
没看见引用Retrofit的地方嘛

### ISSUE THREAD

**Issue by ikkyu0319** [ryanhoo/StylishMusicPlayer#20]

**Comment by DroidPulkit** [comment]
Can you comment the issue in english

**Comment by JerryMissTom** [comment]
He  means  Retrofit is never used in this project

**Comment by ryanhoo** [comment]
@ikkyu0319 Sorry, I haven't used Retrofit in this project yet. But in my plan it will be used to fetch lyrics and album pictures. Actually it should be removed now.
