### ISSUE TITLE
onError

### ISSUE THREAD

**Issue by wangchang163** [ryanhoo/StylishMusicPlayer#3]
![qq 20160919102136](https://cloud.githubusercontent.com/assets/12017058/18621232/c47674ec-7e52-11e6-9b6d-39d18e483f2a.png)

**Comment by xiaofeiMophsic** [comment]
我也碰到这个问题了，其实是在给displayName赋值的时候如果没取到歌曲名简单粗暴给了个null，我在displayName的set方法中吧null替换成空串凑和用了。:D

**Comment by ryanhoo** [comment]
在提取歌曲信息的时候我特意采用了 `MediaMetadataRetriever` 来实现，而没有去查询 android content provider 里的数据库结构化信息，因为后者会经常出现乱码。
歌曲名字为 null(title, displayName) 可能是因为没有取到对应信息，已经默认设置 `file.getName()` 为缺省歌曲名，应该不会再出现这个问题了。
