### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by LxzBUG** [ryanhoo/StylishMusicPlayer#5]
![alt text](https://thumbnail0.baidupcs.com/thumbnail/3e89f697ec929d03522b12846078e051?fid=407604353-250528-710850029261219&time=1474272000&rt=sh&sign=FDTAER-DCb740ccc5511e5e8fedcff06b081203-N4njzhdAHDUa2%2BShGPRMs%2FmKwTU%3D&expires=8h&chkv=0&chkbd=0&chkpc=&dp-logid=6092105316068186514&dp-callid=0&size=c710_u400&quality=100)

第一次进去点右边那个就报错了

**Comment by ryanhoo** [comment]
我的💻拿去修了，麻烦修复下，欢迎 pull request。

**Comment by ryanhoo** [comment]
@LxzBUG 图已经看不到了，能麻烦再提供下吗？
