### ISSUE TITLE
download apk 

### ISSUE THREAD

**Issue by Onasume** [ryanhoo/StylishMusicPlayer#6]
download apk ?

**Comment by rjhsmile** [comment]
哈哈哈哈哦啊

**Comment by ryanhoo** [comment]
This project isn't ready to release yet. I have no idea why so many programmers knew this thing. My computer was broken and I sent it to the Apple Store. Later on I will continue this project. I am sorry but if you want an apk then you will have to compile it on your own.

**Comment by pushcx** [comment]
The project was featured in the "GitHub Explore" weekly newsletter, which I think comes from their "Trending" page.

**Comment by rayliverified** [comment]
Also published on MaterialUp and won Top Project of the Day! Almost 9000 views from there :D 
https://www.uplabs.com/posts/stylishmusicplayer
