### ISSUE TITLE
PlayListDetailsActivity中删除操作重复

### ISSUE THREAD

**Issue by JerryMissTom** [ryanhoo/StylishMusicPlayer#9]
PlayListDetailsActivity的onSongDeleted方法中，执行两次mAdapter.notifyItemRemoved(mDeleteIndex);

**Comment by ryanhoo** [comment]
愚蠢的 bug，本意是 notifyItemRemoved 后更新 footer 的，应该是按下了 CMD+D 后跑去干别的事情忘记了。
Thanks, [57121a1](https://github.com/ryanhoo/StylishMusicPlayer/commit/57121a106af0a9d7cdd12e0d7af2009e9479344e).
